Repository osamhack2022-v2/WEB_CLOUD_OmilZomil_NAVYeffect, pull requests merged in 2022-10, with the labels that each got.

#61 Camera web(be)
  DB_BE/README.md
  DB_BE/docker-compose.yml
  WEB_BE/.gitignore
  WEB_BE/README.md
  WEB_BE/app/camera/crud.py
  WEB_BE/app/camera/model.py
  WEB_BE/app/camera/router.py
  WEB_BE/app/camera/schema.py
  WEB_BE/app/streaming/router.py
  WEB_BE/app/streaming/socket.py
  WEB_BE/app/test/router.py
  WEB_BE/app/token/jwt.py
  WEB_BE/app/token/router.py
  WEB_BE/app/token/schema.py
  WEB_BE/app/token/user.py
  WEB_BE/app/user/crud.py
  WEB_BE/app/user/model.py
  WEB_BE/app/user/router.py
  WEB_BE/app/user/schema.py
  WEB_BE/core/base_schema.py
  WEB_BE/core/db.py
  WEB_BE/core/db_info.py
  WEB_BE/core/settings.py
  WEB_BE/docker-compose.yml
  WEB_BE/docker/Dockerfile
  WEB_BE/docker/enter_docker.sh
  WEB_BE/docker/get-docker.sh
  WEB_BE/docker/git_pull.sh
  WEB_BE/docker/install_docker.sh
  WEB_BE/docker/make_ssl.sh
  WEB_BE/docker/requirements.txt
  WEB_BE/entrypoint.sh
  WEB_BE/init_db.py
  WEB_BE/main.py
  WEB_BE/readme.md
  WEB_BE/static/camera/index.html
  WEB_BE/static/user/index.html
  WEB_BE/test_main.py
Labels: help wanted, question

#72 동정복 인식모델 수정 (계급장 인식, 리턴값)
  AI_BE/OZEngine/dress_checkers/FullDressUniformChecker.py
  AI_BE/OZEngine/dress_checkers/NavyServiceUniformChecker.py
  AI_BE/OZEngine/model.py
Labels: enhancement

#88 Backend에서 사용하기 편하게 변경
  AI_BE/.gitignore
  AI_BE/OZEngine/dress_checkers/FullDressUniformChecker.py
  AI_BE/OZEngine/edge_detectors/HED/__init__.py
  AI_BE/OZEngine/lib/utils.py
  AI_BE/OZEngine/model.py
  AI_BE/OZEngine/person_detectors/PersonDetector.py
  AI_BE/demo/demo_lib/__init__.py
  AI_BE/demo/demo_lib/utils.py
  AI_BE/demo/image/full_dress_uniform/3.jpg
  AI_BE/demo/image/full_dress_uniform/4.jpg
  AI_BE/demo/image/full_dress_uniform/person/1.jpg
  AI_BE/demo/image/full_dress_uniform/person/10.jpg
  AI_BE/demo/image/full_dress_uniform/person/11.jpg
  AI_BE/demo/image/full_dress_uniform/person/12.jpg
  AI_BE/demo/image/full_dress_uniform/person/14.jpg
  AI_BE/demo/image/full_dress_uniform/person/16.jpg
  AI_BE/demo/image/full_dress_uniform/person/17.jpg
  AI_BE/demo/image/full_dress_uniform/person/2.jpg
  AI_BE/demo/image/full_dress_uniform/person/3.jpg
  AI_BE/demo/image/full_dress_uniform/person/4.jpg
  AI_BE/demo/image/full_dress_uniform/person/5.jpg
  AI_BE/demo/image/full_dress_uniform/person/6.jpg
  AI_BE/demo/image/full_dress_uniform/person/7.jpg
  AI_BE/demo/image/full_dress_uniform/person/9.jpg
  AI_BE/demo/image/militery_uniform/1.jpg
  AI_BE/demo/image/militery_uniform/2.jpg
  AI_BE/demo/image/navy_service_uniform/6.jpg
  AI_BE/demo/image/navy_service_uniform/person/0.jpg
  AI_BE/demo/image/navy_service_uniform/person/1.jpg
  AI_BE/demo/image/navy_service_uniform/person/2.jpg
  AI_BE/demo/image/navy_service_uniform/person/3.jpg
  AI_BE/demo/image/navy_service_uniform/person/4.jpg
  AI_BE/demo/image/navy_service_uniform/person/5.jpg
  AI_BE/demo/image/navy_service_uniform/person/6.jpg
  AI_BE/demo/image/navy_service_uniform/person/7.jpg
  AI_BE/demo/main.py
  AI_BE/demo/preprocess/image_preprocess.py
  AI_BE/legacy
  AI_BE/main.ipynb
  AI_BE/main.py
  AI_BE/person_rec_test.ipynb
  AI_BE/requirements.txt
  AI_BE/test.py
Labels: enhancement, good first issue

#119 DEMO video 전용 모듈 구현
  ai/.gitignore
  ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  ai/OZEngine/model.py
  ai/demo/demo_lib/__init__.py
  ai/demo/demo_lib/utils.py
  ai/demo/main.ipynb
  ai/demo/main.py
  ai/demo/preprocess/image_preprocess.py
  ai/demo/preprocess/video2image.py
  ai/legacy
  ai/main.py
  ai/person_rec_test.ipynb
  ai/readme.md
  ai/requirements.txt
  ai/test.py
Labels: enhancement

#120 development -> backend PR
  ai/.gitignore
  ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  ai/OZEngine/model.py
  ai/demo/demo_lib/__init__.py
  ai/demo/demo_lib/utils.py
  ai/demo/main.ipynb
  ai/demo/main.py
  ai/demo/preprocess/image_preprocess.py
  ai/demo/preprocess/video2image.py
  ai/legacy
  ai/main.py
  ai/person_rec_test.ipynb
  ai/readme.md
  ai/requirements.txt
  ai/test.py
Labels: bug

#122 부대출입기록 및 장병 데이터베이스 스키마 및 ORM 설계
  backend/src/app/base_access/crud.py
  backend/src/app/base_access/model.py
  backend/src/app/base_access/schema.py
  backend/src/app/enlisted_personnel/crud.py
  backend/src/app/enlisted_personnel/model.py
  backend/src/app/enlisted_personnel/router.py
  backend/src/app/enlisted_personnel/schema.py
  backend/src/init_db.py
Labels: enhancement

#124 #114 github action을 통해 테스트 및 배포 진행
  .github/workflows/main.yml
Labels: enhancement

#131 계급, 부대 DB 구현 완료
  backend/src/app/api/api.py
  backend/src/app/api/endpoints/enlisted_personnel.py
  backend/src/app/api/endpoints/military_unit.py
  backend/src/app/crud/military_unit.py
  backend/src/app/crud/rank.py
  backend/src/app/db/init_db.py
  backend/src/app/models/military_unit.py
  backend/src/app/models/rank.py
  backend/src/app/schemas/military_unit.py
Labels: enhancement

#139 body-segmentation 대신 다른 방법으로 변경
  ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  ai/OZEngine/dress_checkers/NavyServiceUniformChecker.py
  ai/OZEngine/dress_classifier/__init__.py
  ai/OZEngine/dress_classifier/classificate.py
  ai/OZEngine/face_detectors/FaceDetector.py
  ai/OZEngine/face_detectors/__init__.py
  ai/OZEngine/lib/ocr.py
  ai/OZEngine/model.py
Labels: enhancement

#141 유저 검색 및 필터 기능 추가
  backend/src/app/api/endpoints/user.py
  backend/src/app/crud/user.py
  backend/src/app/schemas/user.py
Labels: enhancement

#137 #113 fastapi vue 연결 완료
  .env.public
  .github/workflows/main.yml
  .gitignore
  ai/Dockerfile
  ai/demo/main.py
  ai/docker-compose.yml
  ai/entrypoint.sh
  ai/main.py
  ai/requirements.txt
  backend/Dockerfile
  backend/README.md
  backend/deploy/Dockerfile
  backend/entrypoint.sh
  backend/requirements.txt
  backend/src/app/main.py
  backend/src/app/static/.keep
  build.sh
  dev_shell.sh
  docker-compose.yml
  front_build.sh
  frontend/.gitignore
  frontend/Dockerfile
  frontend/omilzomil/entrypoint.sh
  package-lock.json
  package.json
  start.sh
Labels: good first issue, help wanted

#166 랭킹페이지 제작
  omilzomil/frontend/src/assets/icons/first.svg
  omilzomil/frontend/src/assets/icons/next.svg
  omilzomil/frontend/src/assets/icons/prev.svg
  omilzomil/frontend/src/assets/icons/second.svg
  omilzomil/frontend/src/assets/icons/third.svg
  omilzomil/frontend/src/components/RankingCard.vue
  omilzomil/frontend/src/router/index.js
  omilzomil/frontend/src/views/RankingPage.vue
Labels: new feature

#170 일반 사용자 계정으로 빌드시 발생하는 오류 수정
  build.sh
  omilzomil/frontend.Dockerfile
  start.sh
  webrtc/frontend.Dockerfile
Labels: bug fix

#174 랭킹페이지 반응형 추가
  omilzomil/frontend/src/views/RankingPage.vue
Labels: new feature

#180 회원탈퇴 페이지 반응형 추가
  omilzomil/frontend/src/assets/icons/crying-face.svg
  omilzomil/frontend/src/assets/icons/eye-off.svg
  omilzomil/frontend/src/assets/icons/eye-on.svg
  omilzomil/frontend/src/assets/images/box.svg
  omilzomil/frontend/src/assets/images/unregist.svg
  omilzomil/frontend/src/router/index.js
  omilzomil/frontend/src/views/UnregisterPage.vue
Labels: new feature

#184 데모페이지 프론트, 백 연결, 통신 테스트
  webrtc/frontend/src/views/CameraView.vue
Labels: new feature

#181 devops 정상동작 확인 완료
  .gitignore
  build.sh
  docker-compose.yml
  omilzomil/backend.Dockerfile
  omilzomil/backend/requirements.txt
  omilzomil/frontend.Dockerfile
  start.sh
  webrtc/backend.Dockerfile
  webrtc/backend/requirements.txt
  webrtc/frontend.Dockerfile
  webrtc/install_docker.sh
Labels: help wanted, bug fix, CI/CD

#188 누락 파일 재생성
  omilzomil/backend/src/app/core/security.py
Labels: bug fix

#182 회원탈퇴 페이지 디자인 수정
  omilzomil/frontend/src/assets/icons/crying-face.svg
  omilzomil/frontend/src/assets/images/unregist.svg
  omilzomil/frontend/src/views/UnregisterPage.vue
Labels: feature improve

#199 백앤드 배포 변경에 따른 통합
  docker-compose.yml
  webrtc/backend/src/app/api/endpoints/recording.py
  webrtc/backend/src/app/main.py
Labels: branch work

#178 #114 github action으로 배포 자동화
  .github/workflows/main.yml
  omilzomil/backend/entrypoint.sh
  webrtc/backend/entrypoint.sh
  webrtc/backend/src/app/main.py
Labels: CI/CD

#198 deploy용 dev용 분리
  .env.public
  build.sh
  docker-compose.yml
  start.sh
Labels: CI/CD, feature improve

#218 도커 볼륨 미삭제 오류 해결
  build.sh
  omilzomil/backend/src/app/api/api.py
  omilzomil/backend/src/app/api/deps.py
  omilzomil/backend/src/app/api/endpoints/login.py
  omilzomil/backend/src/app/api/endpoints/military_unit.py
  omilzomil/backend/src/app/crud/military_unit.py
  omilzomil/backend/src/app/crud/token.py
  omilzomil/backend/src/app/crud/user.py
  omilzomil/backend/src/app/db/init_db.py
  omilzomil/backend/src/app/models/military_unit.py
  omilzomil/backend/src/app/models/role.py
  omilzomil/backend/src/app/schemas/military_unit.py
  omilzomil/backend/src/app/schemas/token.py
  omilzomil/backend/src/app/schemas/user.py
  omilzomil/frontend/src/App.vue
  omilzomil/frontend/src/assets/icons/alert-error.svg
  omilzomil/frontend/src/assets/icons/eye-off.svg
  omilzomil/frontend/src/assets/icons/eye-on.svg
  omilzomil/frontend/src/assets/icons/first.svg
  omilzomil/frontend/src/assets/icons/mdi_chevron-down.svg
  omilzomil/frontend/src/assets/icons/next.svg
  omilzomil/frontend/src/assets/icons/prev.svg
  omilzomil/frontend/src/assets/icons/second.svg
  omilzomil/frontend/src/assets/icons/third.svg
  omilzomil/frontend/src/assets/images/Thumb_up.png
  omilzomil/frontend/src/assets/images/box.svg
  omilzomil/frontend/src/assets/images/clap/back.svg
  omilzomil/frontend/src/assets/images/clap/effect.svg
  omilzomil/frontend/src/assets/images/clap/front.svg
  omilzomil/frontend/src/assets/images/dashboard.png
  omilzomil/frontend/src/assets/images/photo.svg
  omilzomil/frontend/src/assets/images/photoback.svg
  omilzomil/frontend/src/assets/images/problem-background.png
  omilzomil/frontend/src/assets/images/soldier.png
  omilzomil/frontend/src/assets/logo.svg
  omilzomil/frontend/src/assets/logo1.svg
  omilzomil/frontend/src/assets/styles/common.css
  omilzomil/frontend/src/components/AppBar.vue
  omilzomil/frontend/src/components/DetailCard.vue
  omilzomil/frontend/src/components/EventCard.vue
  omilzomil/frontend/src/components/common/SearchInput.vue
  omilzomil/frontend/src/components/dashboard/EventCard.vue
  omilzomil/frontend/src/components/dashboard/TitleCard.vue
  omilzomil/frontend/src/components/profile/editProfile.vue
  omilzomil/frontend/src/components/profile/unitManagement.vue
  omilzomil/frontend/src/components/profile/userManagement.vue
  omilzomil/frontend/src/components/totaldash/LineCard.vue
  omilzomil/frontend/src/components/totaldash/MonthCard.vue
  omilzomil/frontend/src/router/index.js
  omilzomil/frontend/src/views/DashBoardPage.vue
  omilzomil/frontend/src/views/EventCardTest.vue
  omilzomil/frontend/src/views/LandingPage.vue
  omilzomil/frontend/src/views/LoginPage.vue
  omilzomil/frontend/src/views/ProfilePage.vue
  omilzomil/frontend/src/views/RankingPage.vue
  omilzomil/frontend/src/views/RegistVacationPage.vue
  omilzomil/frontend/src/views/RegisterPage.vue
  omilzomil/frontend/src/views/TotalDashBoardPage.vue
  omilzomil/frontend/src/views/UnregisterPage.vue
  omilzomil/frontend/src/views/VacationPage.vue
Labels: bug fix

#239 정복인식모델 리펙토링 완료
  webrtc/ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/NavyServiceUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/UniformChecker.py
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/0.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/106.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/131.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/152.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/18.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/187.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/206.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/37.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/62.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/navy_service/80.jpg
  webrtc/ai/OZEngine/lib/utils.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/OZEngine/parts_classifier/PartsClassifier.py
  webrtc/ai/OZEngine/person_detectors/PersonDetector.py
Labels: feature improve

#259 #258 파츠인식모델 성능개선, 예외처리 추가
  webrtc/ai/OZEngine/FeatureExtractor.py
  webrtc/ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/UniformChecker.py
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/0.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/1.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/2.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/8.jpg
  webrtc/ai/OZEngine/model.py
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/0.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag/0.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/1.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/2.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/name_tag/0.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/validation_set/name_tag/2.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/classes
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/features.npy
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/img_paths
  webrtc/ai/OZEngine/parts_classifier/PartsClassifier.py
  webrtc/ai/OZEngine/parts_classifier/train.py
Labels: bug fix, AI model, feature improve

#278 웹소켓 프론트엔드
  webrtc/frontend/src/App.vue
  webrtc/frontend/src/assets/icons/black.svg
  webrtc/frontend/src/assets/icons/blue.svg
  webrtc/frontend/src/assets/icons/fail.svg
  webrtc/frontend/src/assets/icons/green.svg
  webrtc/frontend/src/assets/icons/loading.svg
  webrtc/frontend/src/assets/icons/pass.svg
  webrtc/frontend/src/assets/images/test.svg
  webrtc/frontend/src/assets/logo.png
  webrtc/frontend/src/router/index.js
  webrtc/frontend/src/views/AboutView.vue
  webrtc/frontend/src/views/CameraView.vue
  webrtc/frontend/src/views/HomeView.vue
Labels: new feature

#281 오류수정
  webrtc/frontend/src/views/CameraView.vue
Labels: bug fix

#283 오류 해결
  webrtc/frontend/src/views/CameraView.vue
Labels: bug fix

#284 부품분류모델, 복장분류모델 데이터셋 추가 및 학습
  webrtc/ai/OZEngine/FeatureExtractor.py
  webrtc/ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/12.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/full_dress/7.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/model/classes
  webrtc/ai/OZEngine/dress_classifier/Dress/model/features.npy
  webrtc/ai/OZEngine/dress_classifier/Dress/model/img_paths
  webrtc/ai/OZEngine/dress_classifier/DressClassifier.py
  webrtc/ai/OZEngine/dress_classifier/train.py
  webrtc/ai/OZEngine/edge_detectors/HED/__init__.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/288.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/289.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/313.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/314.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/315.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/316.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/anchor/317.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/0.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/269.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/278.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/282.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/286.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/289.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/291.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/294.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/300.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/303.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+1/309.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/class_tag+3/13.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/0.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/12.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/3.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/316.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/317.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/4.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/6.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/mahura/8.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/name_tag/1.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/name_tag/2.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/dataset/train_set/name_tag/5.jpg
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/classes
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/features.npy
  webrtc/ai/OZEngine/parts_classifier/FullDressUniform/model/img_paths
  webrtc/ai/demo/preprocess/video2image.py
Labels: data colect, bug fix, AI model

#307 github action 코드 수정시 반영 확인
  .github/workflows/main.yml
  .gitignore
  build.sh
  docker-compose.yml
  reset.sh
  start.sh
  stop.sh
  webrtc/backend/src/app/main.py
  webrtc/frontend/src/views/AboutView.vue
Labels: CI/CD

#344 development 용 으로 webrtc 포트 변경
  webrtc/frontend/src/views/CameraView.vue
Labels: bug fix, CI/CD

#346 #337 #345 OZEngine model 리펙토링 및 사람인식기능 탈부착 가능
  webrtc/ai/OZEngine/dress_checkers/FullDressUniformChecker.py
  webrtc/ai/OZEngine/lib/utils.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/demo/main.py
  webrtc/ai/requirements.txt
Labels: AI model, feature improve

#380 HED관련 에러 수정
  webrtc/ai/OZEngine/model.py
Labels: bug fix

#381 분류모델 경로재설정, step return 추가
  webrtc/ai/OZEngine/dress_checkers/NavyServiceUniformChecker.py
  webrtc/ai/OZEngine/dress_classifier/DressClassifier.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/OZEngine/parts_classifier/PartsClassifier.py
Labels: feature improve

#396 DB 데이터가 날아가지 않게 보존
  .gitignore
  docker-compose.yml
  webrtc/backend/src/app/api/endpoints/recording.py
Labels: CI/CD

#433 #18 전투복 인식모델 수정 및 추가
  webrtc/ai/OZEngine/dress_checkers/CombatUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/UniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/__init__.py
  webrtc/ai/OZEngine/dress_classifier/Dress/dataset/train_set/combat/1.jpg
  webrtc/ai/OZEngine/dress_classifier/Dress/model/classes
  webrtc/ai/OZEngine/dress_classifier/Dress/model/features.npy
  webrtc/ai/OZEngine/dress_classifier/Dress/model/img_paths
  webrtc/ai/OZEngine/lib/defines.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/dataset/train_set/flag_tag/1.jpg
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/dataset/train_set/insignia_tag/1.jpg
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/dataset/train_set/name_tag/1.jpg
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/dataset/train_set/name_tag/2.jpg
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/dataset/train_set/rank_tag+2/0.jpg
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/model/classes
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/model/features.npy
  webrtc/ai/OZEngine/parts_classifier/CombatUniform/model/img_paths
  webrtc/ai/OZEngine/parts_classifier/PartsClassifier.py
Labels: new feature, AI model, feature improve

#348 Document Merge
  README.md
  webrtc/ai/OZEngine/readme.md
Labels: documentation, feature improve

#438 #437 AI 결과물 padding값 적용 안되는 버그 수정
  webrtc/ai/OZEngine/dress_checkers/CombatUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/UniformChecker.py
  webrtc/ai/OZEngine/model.py
Labels: bug fix

#439 #437 AI 결과물 padding값 적용 안되는 버그 수정
  webrtc/ai/OZEngine/model.py
  webrtc/ai/demo/main.py
Labels: bug fix

#443 #423 배포서버 webrtc endpoint 변경 및 rebuild
  webrtc/frontend/src/views/CameraView.vue
Labels: bug fix

#445 프론트 요구사항으로 key 값을 구버전 으로 수정
  webrtc/backend/src/app/api/image_box/front_adapter.py
  webrtc/backend/src/app/api/worker/single.py
Labels: bug fix

#444 README.md 3개 작성
  LICENSE
  README.md
  omilzomil/Readme.md
  webrtc/Readme.md
  webrtc/ai/OZEngine/readme.md
  webrtc/ai/demo/image_res.jpg
  webrtc/ai/readme.md
Labels: documentation

#441 #437 #18 두발인식모델 추가
  webrtc/ai/.gitignore
  webrtc/ai/OZEngine/dress_checkers/CombatUniformChecker.py
  webrtc/ai/OZEngine/dress_checkers/UniformChecker.py
  webrtc/ai/OZEngine/hair_detectors/HairDetector.py
  webrtc/ai/OZEngine/hair_detectors/__init__.py
  webrtc/ai/OZEngine/lib/defines.py
  webrtc/ai/OZEngine/model.py
  webrtc/ai/demo/demo.ipynb
  webrtc/ai/demo/main.py
  webrtc/ai/demo/test.ipynb
  webrtc/ai/demo/test_rgb.py
Labels: bug fix, AI model

#447 Pull Request to dev branch
  ai/.gitignore
  ai/OZEngine/lib/defines.py
  ai/OZEngine/model.py
  ai/OZEngine/readme.md
  ai/readme.md
  webrtc/ai/OZEngine/hair_detectors/HairDetector.py
  webrtc/ai/OZEngine/hair_detectors/__init__.py
  webrtc/ai/OZEngine/readme.md
  webrtc/ai/demo/demo.ipynb
  webrtc/ai/demo/test.ipynb
  webrtc/ai/demo/test_rgb.py
Labels: AI model, feature improve

#450 ai 코드 업데이트에 따른 webrtc 갱신
  ai/OZEngine/hair_detectors/HariDetector.py
  ai/OZEngine/hair_detectors/__init__.py
  ai/master/master.py
  ai/master/server.py
  ai/worker/worker.py
  webrtc/backend/src/app/api/endpoints/recording.py
  webrtc/backend/src/app/api/image_box/base.py
  webrtc/backend/src/app/api/image_box/db_adapter.py
  webrtc/backend/src/app/api/image_box/front_adapter.py
  webrtc/backend/src/app/api/image_box/image_box.py
  webrtc/backend/src/app/api/simple/image_box.py
  webrtc/backend/src/app/api/simple/worker.py
  webrtc/backend/src/app/api/socket/image_box.py
  webrtc/backend/src/app/api/socket/worker.py
  webrtc/backend/src/app/api/worker/single.py
Labels: feature improve

#448 리드미에 AI 소개, 링크 추가
  LICENSE.md
  README.md
  omilzomil/Readme.md
  webrtc/Readme.md
Labels: documentation

#458 github action main에 반영
  .github/workflows/main.yml
Labels: bug fix
